### ISSUE TITLE
ubuntu and fedora are failing due to some systemd-swap service

### ISSUE THREAD

**Issue by JensWalter** [apimeister/unpatched-agent#9]
fedora-log

```
[root@dtz-edge2 unpatched-agent]# cargo run -- --server ws://192.168.178.86:3000/ws --alias me2
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/unpatched-agent --server 'ws://192.168.178.86:3000/ws' --alias me2`
2023-07-27T11:30:37.888592Z  INFO unpatched_agent: Starting unpatched agent...
2023-07-27T11:30:37.924945Z  INFO unpatched_agent: Connection established and validated via ping message
thread 'tokio-runtime-worker' panicked at 'For "dev-zram0.swap" -> Matching variant not found', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/systemctl-0.3.0/src/lib.rs:456:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', src/main.rs:210:37
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', src/main.rs:210:37
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', src/main.rs:210:37
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', src/main.rs:210:37
```

**Comment by alexkunde** [comment]
refactored - no longer applicable
